### ISSUE TITLE
Learning Curves and Cumulative Regret Calculation

### ISSUE THREAD

**Issue by vkurenkov** [nakamotoo/Cal-QL#1]
👋🏻

Great work, could you please share a couple of details regarding the evaluation?
 - Did you report the `exploration/` curves or the `evaluation/` ones?
 - How did you compute the cumulative regret? Was it also based on exploration or evaluation episodes?

**Comment by nakamotoo** [comment]
Hi! Thanks for reaching out! 
- For the result, we are reporting `evaluation` curves  
- For the average cumulative regret, suppose you are doing online fine-tuning for 5000 env steps, and you have a list of the normalized scores for every 1000 env steps:
```
scores = [0.2, 0.5, 0.7, 1.0, 1.0, 1.0]
env_steps = [0, 1000, 2000, 3000, 4000, 5000]
```
Then you can calculate the regret as  
```
regret = np.mean(1 - normalized_score)
```

**Comment by DT6A** [comment]
> 

Thanks  a  lot  for your reply. But how should we handle regret calculation if scores are outside of 0-1 range? In case of Adroit tasks, for example, it is possible to get score higher than 1.0 and lower than 0.0. Should the scores be clipped in that cases?

**Comment by nakamotoo** [comment]
Hi! For the Adroit task, we are using the evaluation/goal_achieved_rate as our metric, which will be in the range of 0-1.

However, for any metric that spans a different range, specifically from `min_possible_score` to `max_possible_score`, you can normalize your scores to a 0-1 range as follows:
```
normalized_score = (score - min_possible_score) / (max_possible_score - min_possible_score)
```

**Comment by DT6A** [comment]
@nakamotoo got it. Thank you for your answer!
