### ISSUE TITLE
adroit environments are not actually sparse

### ISSUE THREAD

**Issue by trevormcinroe** [nakamotoo/Cal-QL#6]
In the paper, the adroit environments are described as being sparse: "The agent obtains a sparse binary +1/0 reward if it succeeds in solving the task".

But, the code actually makes them not sparse due to `reward_scale` and `reward_bias` in: https://github.com/nakamotoo/Cal-QL/blob/main/scripts/run_adroit.sh#L30-L31

Is the code incorrect?

**Comment by nakamotoo** [comment]
Hi, we rescaled the reward from -1/0 to -5/+5, but it is still sparse in the sense that the trajectory contains only two values -- positive and negative rewards. We found that rescaling the reward can make CQL/Cal-QL train more stably.
